version: '3.9'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    env_file: .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - db
    ports:
      - "8000:8000"
    restart: unless-stopped
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    env_file: .env
    depends_on:
      - backend
    ports:
      - "3000:3000"
    restart: unless-stopped
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: linkdive_prod
      POSTGRES_USER: linkdive
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-password}
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U linkdive"]
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
    image: redis:7-alpine
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
volumes:
  pg_data: {}
